config/routes.rb
Cap::Application.routes.draw do
  devise_for :users, :controllers => {confirmations: 'confirmations'}

  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  root :to => 'admin#index'

  match 'admin' => 'admin#index'
  namespace :admin do 
    resources :groups, :only => [ :edit, :create, :new, :update, :destroy]
    resources :users, :only => [:new, :create, :index, :destroy, :edit, :update ]
  end

   

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
          :recoverable, :rememberable #, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :group_id

  validates :group_id, :presence => true

  def self.accessible_users_for(group) 
    allowed_group_ids = Group.allowed_groups(group).map { |group| group.id}
    User.where(group_id: allowed_group_ids)
  end

  def accessible_users
    User.accessible_users_for group
  end
  
  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] = "Password can't be blank" if password.blank?
    self.errors[:password_confirmation] = "Password confirmation can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] = "password_confirmation does not match the password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def accessible_groups
    #returns a query object containing the user's group and it's children
    Group.allowed_groups(group)
  end
  
  def self.get_admins
    User.where(admin: true)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    #get users by group for the allowed groups
    @users_by_group = current_user.group.users_by_allowed_groups
  end


  def new
    begin
      #TODO: add allowed groups by loggedin admin!!
      @group = Group.find(params[:group_id])
      @user = @group.users.build
    rescue ActiveRecord::RecordNotFound => e
      p "whoops: " + e.message
      flash[:error] = "Sorry, but no matching group was found"
      redirect_to admin_path
    end
  end

  def create
    #TODO: add allowed groups by loggedin admin!!
    @user = User.new(params[:user])
    if @user.save
      redirect_to admin_path, notice: "A confirmation was sent to #{@user.email}."
    else
      flash[:error] = "This user could not be created"
      render :edit
    end
  end

  def destroy
    victem = current_user.accessible_users.find_by_id!(params[:id])
    if victem.destroy
      redirect_to admin_path, notice: "The account for '#{victem.email}' was permanently deleted"
    else
      flash[:error] = "The account for '#{victem.email}' could not be deleted"
      redirect_to admin_path
    end
  end

  def edit
    @user = current_user.accessible_users.find_by_id(params[:id])
    @allowed_groups = current_user.accessible_groups.to_a
    redirect_to  admin_users_path, notice: "The requested user does not exist or is not accessible." unless @user

  end

  def update
    p params
    admin = params[:user][:admin] == "1"
    @user = current_user.accessible_users.find_by_id!(params[:id])
    @allowed_groups = current_user.accessible_groups.to_a
    if @user.blank?
      redirect_to admin_users_path, notice: "The requested user does not exist or is not accessible."
    else
      unless @user.update_attributes(params[:user].reject!{|k| k== "admin"})
        flash[:error] = "The user could not be updated - sorry"
      end
      p admin
      @user.admin = admin
      @user.save!
      redirect_to admin_users_path
    end
  end

  private

end

app/views/admin/users/edit.html.haml
%h1= "Edit user"

=form_for @user, url: admin_user_path, html: {id: "new_user"} do |f|
  %p
    =f.label "Group"
    =f.collection_select :group_id, @allowed_groups, :id, :name, selected: @user.group_id
  %p
    =f.label :email
    =f.text_field :email

  %p
    =f.label :admin
    =f.check_box("admin")
  %p
    =f.submit

=link_to "Back", admin_users_path

app/views/admin/users/index.html.haml
-content_for :title do "Capex User Admin Page" end

%h1 Capex User Admin Page

%table#group_table.table
  %tr
    %th Group
    %th User
    %th Admin
    %th
  -@users_by_group.keys.each do |group_id|
    %tr
      %td= group_with_depth(Group.find_by_id(group_id))
      %td
      %td    
      %td
    - @users_by_group[group_id].each do |user|
      %tr
        %td
        %td
          = user.email
          - unless user.confirmed?
            %i.icon-envelope{style:"color:red;", "data-toggle"=>"tooltip", "title"=>"User has not confirmed account"}
        %td
          -if user.admin
            %i.icon-ok{style:"color:green"}
        %td 
          =link_to(edit_admin_user_path(user), id: "edit_user_#{user.id}_link", class: "btn")  do
            <i class="icon-pencil"></i> Edit
          - warning = "Are you sure that you want to permanently delete the account for '#{user.email}'?"
          = link_to admin_user_path(user), {confirm: warning, method: "delete", id: "delete_user_#{user.id}_button", class: "btn"} do
            <i class="icon-trash"></i> Delete User
            

app/views/admin/users/new.html.haml
%h1= "Create a new user for group: #{@group.name}"

=form_for @user, url: url_for(controller: "admin/users", action: "create"), html: {id: "new_user"} do |f|
  =f.hidden_field :group_id, value: @group.id
  %p
    =f.label :email
    =f.text_field :email

  %p
    =f.submit